package com.training.platform.notification.entity;

public enum NotificationType {
    CHAT_MESSAGE,
    ENROLLMENT_CONFIRMED,
    ENROLLMENT_WAITLISTED,
    ENROLLMENT_APPROVED,
    ENROLLMENT_CANCELLED,
    SESSION_STARTED,
    SESSION_REMINDER,
    SESSION_CANCELLED,
    SESSION_RESCHEDULED,
    SESSION_COMPLETED,
    FORMATION_COMPLETED
}
