sonar.projectKey=training-platform
sonar.projectName=Training Platform
sonar.sources=backend/src/main/java
sonar.tests=backend/src/test/java
sonar.java.binaries=backend/target/classes
sonar.coverage.jacoco.xmlReportPaths=backend/target/site/jacoco/jacoco.xml
sonar.exclusions=**/dto/**,**/entity/**,**/config/DataSeeder.java
