package com.training.platform.learner.service;

import com.training.platform.catalogue.formation.entity.Formation;
import com.training.platform.catalogue.formation.repository.FormationRepository;
import com.training.platform.catalogue.formation.service.FormationService;
import com.training.platform.enrollment.repository.EnrollmentRepository;
import com.training.platform.learner.dto.ImprovementPlanResponse;
import com.training.platform.learner.dto.ImprovementPriority;
import com.training.platform.learner.dto.ImprovementSuggestion;
import com.training.platform.learner.dto.LearnerProfileScoreResponse;
import com.training.platform.learner.dto.SkillGapAnalysisResponse;
import com.training.platform.learner.entity.LearnerProfile;
import com.training.platform.formation.dto.FormationProgressSnapshot;
import com.training.platform.formation.service.FormationProgressService;
import com.training.platform.ml.dto.MlFormationPayload;
import com.training.platform.ml.dto.MlProfilePayload;
import com.training.platform.ml.dto.MlSuggestRequest;
import com.training.platform.ml.dto.MlSuggestResponse;
import com.training.platform.ml.dto.MlSuggestionItem;
import com.training.platform.ml.service.MlSuggestionClient;
import com.training.platform.session.entity.SessionStatus;
import com.training.platform.session.repository.TrainingSessionRepository;
import com.training.platform.skill.entity.Skill;
import java.util.ArrayList;
import java.util.Comparator;
import java.text.Normalizer;
import java.util.HashMap;
import java.util.List;
import java.util.Locale;
import java.util.Map;
import java.util.Optional;
import java.util.Set;
import java.util.stream.Collectors;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import org.springframework.util.StringUtils;

@Service
public class LearnerIntelligenceService {

    private final LearnerProfileService learnerProfileService;
    private final FormationService formationService;
    private final FormationRepository formationRepository;
    private final TrainingSessionRepository trainingSessionRepository;
    private final EnrollmentRepository enrollmentRepository;
    private final FormationProgressService formationProgressService;
    private final MlSuggestionClient mlSuggestionClient;

    public LearnerIntelligenceService(
            LearnerProfileService learnerProfileService,
            FormationService formationService,
            FormationRepository formationRepository,
            TrainingSessionRepository trainingSessionRepository,
            EnrollmentRepository enrollmentRepository,
            FormationProgressService formationProgressService,
            MlSuggestionClient mlSuggestionClient
    ) {
        this.learnerProfileService = learnerProfileService;
        this.formationService = formationService;
        this.formationRepository = formationRepository;
        this.trainingSessionRepository = trainingSessionRepository;
        this.enrollmentRepository = enrollmentRepository;
        this.formationProgressService = formationProgressService;
        this.mlSuggestionClient = mlSuggestionClient;
    }

    @Transactional(readOnly = true)
    public LearnerProfileScoreResponse profileScore(String email) {
        return calculateProfileScore(learnerProfileService.getByUserEmail(email));
    }

    @Transactional(readOnly = true)
    public SkillGapAnalysisResponse skillGap(String email, Long formationId) {
        LearnerProfile learner = learnerProfileService.getByUserEmail(email);
        Formation formation = formationService.getFormation(formationId);
        return analyzeSkillGap(learner, formation);
    }

    @Transactional(readOnly = true)
    public ImprovementPlanResponse improvementPlan(String email) {
        LearnerProfile learner = learnerProfileService.getByUserEmail(email);
        LearnerProfileScoreResponse score = calculateProfileScore(learner);
        Set<Long> completedFormationIds = completedFormationIds(email, learner.getId());
        List<Formation> formations = formationRepository.findTop20ByActiveTrueOrderByCreatedAtDesc();

        Optional<MlSuggestResponse> mlResponse = requestMlSuggestions(learner, formations);
        if (mlResponse.isPresent()) {
            List<ImprovementSuggestion> suggestions = mergeMlSuggestions(
                    learner, formations, completedFormationIds, mlResponse.get()
            );
            boolean hasNext = suggestions.stream().anyMatch(s -> s.priority() != ImprovementPriority.DONE);
            return new ImprovementPlanResponse(
                    learner.getId(),
                    score.score(),
                    "MLA",
                    hasNext
                            ? "Suggestions generated by the MLA profile-analysis model."
                            : "No formation currently suited to your profile. Update your skills or learning goals, or wait for new catalogue offerings.",
                    suggestions
            );
        }

        List<ImprovementSuggestion> rules = ruleBasedSuggestions(learner, formations, completedFormationIds);
        boolean hasNext = rules.stream().anyMatch(s -> s.priority() != ImprovementPriority.DONE);
        return new ImprovementPlanResponse(
                learner.getId(),
                score.score(),
                "RULES",
                hasNext
                        ? "Suggestions from rule-based fallback (MLA service unavailable)."
                        : "No formation currently suited to your profile. Complete your skills and learning goals for better matching.",
                rules
        );
    }

    private Optional<MlSuggestResponse> requestMlSuggestions(LearnerProfile learner, List<Formation> formations) {
        String level = learner.getCurrentLevel() == null ? "BEGINNER" : learner.getCurrentLevel().name();
        List<String> skills = skillNames(learner.getSkills());
        String goals = learner.getLearningGoals() == null ? "" : learner.getLearningGoals();
        List<MlFormationPayload> payload = formations.stream()
                .map(formation -> new MlFormationPayload(
                        formation.getId(),
                        formation.getTitle(),
                        formation.getLevel() == null ? "BEGINNER" : formation.getLevel().name(),
                        skillNames(formation.getRequiredSkills()),
                        formation.getCategory() == null ? "" : formation.getCategory().getName()
                ))
                .toList();
        return mlSuggestionClient.suggest(new MlSuggestRequest(new MlProfilePayload(level, skills, goals), payload));
    }

    private static final double MLA_MIN_SCORE = 0.50;

    private List<ImprovementSuggestion> mergeMlSuggestions(
            LearnerProfile learner,
            List<Formation> formations,
            Set<Long> completedFormationIds,
            MlSuggestResponse mlResponse
    ) {
        Map<Long, Formation> byId = formations.stream()
                .collect(Collectors.toMap(Formation::getId, formation -> formation, (left, right) -> left, HashMap::new));
        Map<Long, ImprovementSuggestion> base = new HashMap<>();
        for (Formation formation : formations) {
            base.put(formation.getId(), toSuggestion(learner, formation, completedFormationIds.contains(formation.getId())));
        }

        boolean profileTooThin = isProfileTooThin(learner);
        List<ImprovementSuggestion> next = new ArrayList<>();
        List<MlSuggestionItem> ranked = mlResponse.suggestions() == null ? List.of() : mlResponse.suggestions();
        for (MlSuggestionItem item : ranked) {
            if (profileTooThin || item.score() < MLA_MIN_SCORE) {
                continue;
            }
            Formation formation = byId.get(item.formationId());
            if (formation == null) {
                continue;
            }
            ImprovementSuggestion existing = base.get(item.formationId());
            if (existing == null || existing.priority() == ImprovementPriority.DONE) {
                continue;
            }
            next.add(enrichWithMl(existing, item));
            if (next.size() >= 5) {
                break;
            }
        }

        List<ImprovementSuggestion> done = base.values().stream()
                .filter(suggestion -> suggestion.priority() == ImprovementPriority.DONE)
                .toList();
        List<ImprovementSuggestion> suggestions = new ArrayList<>(next);
        suggestions.addAll(done);
        return suggestions;
    }

    private boolean isProfileTooThin(LearnerProfile learner) {
        boolean noSkills = learner.getSkills() == null || learner.getSkills().isEmpty();
        boolean noGoals = !StringUtils.hasText(learner.getLearningGoals());
        return noSkills && noGoals;
    }

    private ImprovementSuggestion enrichWithMl(ImprovementSuggestion base, MlSuggestionItem mlItem) {
        List<String> reasons = new ArrayList<>();
        if (mlItem.reasons() != null) {
            reasons.addAll(mlItem.reasons());
        }
        for (String reason : base.reasons()) {
            if (!reasons.contains(reason)) {
                reasons.add(reason);
            }
        }
        return new ImprovementSuggestion(
                base.formationId(),
                base.formationTitle(),
                base.categoryName(),
                base.level(),
                base.matchPercentage(),
                base.missingSkills(),
                reasons,
                priorityFromMlScore(mlItem.score(), base.priority()),
                base.formationProgressPercentage(),
                base.completedSessions(),
                base.totalSessions()
        );
    }

    private ImprovementPriority priorityFromMlScore(double score, ImprovementPriority fallback) {
        if (fallback == ImprovementPriority.DONE) {
            return ImprovementPriority.DONE;
        }
        if (score >= 0.7) {
            return ImprovementPriority.HIGH;
        }
        if (score >= 0.4) {
            return ImprovementPriority.MEDIUM;
        }
        return ImprovementPriority.LOW;
    }

    private List<ImprovementSuggestion> ruleBasedSuggestions(
            LearnerProfile learner,
            List<Formation> formations,
            Set<Long> completedFormationIds
    ) {
        List<ImprovementSuggestion> ranked = formations.stream()
                .map(formation -> toSuggestion(learner, formation, completedFormationIds.contains(formation.getId())))
                .toList();

        List<ImprovementSuggestion> next = ranked.stream()
                .filter(suggestion -> suggestion.priority() != ImprovementPriority.DONE)
                .filter(suggestion -> !isProfileTooThin(learner))
                .filter(suggestion -> suggestion.matchPercentage() >= 40
                        || suggestion.reasons().stream().anyMatch(reason -> reason.contains("learning goals")))
                .sorted(Comparator
                        .comparing((ImprovementSuggestion suggestion) -> suggestion.reasons().contains("Matches your learning goals."), Comparator.reverseOrder())
                        .thenComparing(ImprovementSuggestion::priority)
                        .thenComparing(ImprovementSuggestion::matchPercentage, Comparator.reverseOrder()))
                .limit(5)
                .toList();

        List<ImprovementSuggestion> done = ranked.stream()
                .filter(suggestion -> suggestion.priority() == ImprovementPriority.DONE)
                .toList();

        List<ImprovementSuggestion> suggestions = new ArrayList<>(next);
        suggestions.addAll(done);
        return suggestions;
    }

    LearnerProfileScoreResponse calculateProfileScore(LearnerProfile profile) {
        int score = 0;
        List<String> completed = new ArrayList<>();
        List<String> missing = new ArrayList<>();

        if (StringUtils.hasText(profile.getUser().getFirstName()) && StringUtils.hasText(profile.getUser().getLastName())) {
            score += 15;
            completed.add("name");
        } else {
            missing.add("name");
        }
        score += scoreField(profile.getPhone(), "phone", 15, completed, missing);
        score += scoreField(profile.getBio(), "bio", 15, completed, missing);
        if (profile.getCurrentLevel() != null) {
            score += 15;
            completed.add("currentLevel");
        } else {
            missing.add("currentLevel");
        }
        if (profile.getSkills() != null && !profile.getSkills().isEmpty()) {
            score += 20;
            completed.add("skills");
        } else {
            missing.add("skills");
        }
        score += scoreField(profile.getLearningGoals(), "learningGoals", 20, completed, missing);

        return new LearnerProfileScoreResponse(Math.min(score, 100), completed, missing, scoreMessage(score));
    }

    SkillGapAnalysisResponse analyzeSkillGap(LearnerProfile learner, Formation formation) {
        List<String> learnerSkills = skillNames(learner.getSkills());
        List<String> requiredSkills = skillNames(formation.getRequiredSkills());

        if (requiredSkills.isEmpty()) {
            return new SkillGapAnalysisResponse(
                    learner.getId(),
                    formation.getId(),
                    formation.getTitle(),
                    learnerSkills,
                    requiredSkills,
                    List.of(),
                    List.of(),
                    100,
                    true,
                    "No required skills defined for this formation."
            );
        }

        Set<String> learnerSkillKeys = learnerSkills.stream()
                .map(this::normalize)
                .collect(Collectors.toSet());
        List<String> matching = requiredSkills.stream()
                .filter(skill -> learnerSkillKeys.contains(normalize(skill)))
                .toList();
        List<String> missing = requiredSkills.stream()
                .filter(skill -> !learnerSkillKeys.contains(normalize(skill)))
                .toList();
        int percentage = (int) Math.round((matching.size() * 100.0) / requiredSkills.size());
        boolean ready = percentage >= 60;

        return new SkillGapAnalysisResponse(
                learner.getId(),
                formation.getId(),
                formation.getTitle(),
                learnerSkills,
                requiredSkills,
                matching,
                missing,
                percentage,
                ready,
                ready ? "You are ready to start this formation." : "You should improve the missing skills before starting this formation."
        );
    }

    private ImprovementSuggestion toSuggestion(LearnerProfile learner, Formation formation, boolean completed) {
        SkillGapAnalysisResponse gap = analyzeSkillGap(learner, formation);
        FormationProgressSnapshot progress = formationProgressService.snapshot(learner.getId(), formation.getId());
        List<String> reasons = new ArrayList<>();
        boolean goalsMatch = goalsMatch(learner, formation);
        if (completed) {
            reasons.add("You completed all sessions of this formation.");
        } else if (progress.completedSessions() > 0 && progress.totalSessions() > 0) {
            reasons.add(progress.completedSessions() + " of " + progress.totalSessions() + " sessions completed.");
        }
        if (goalsMatch) {
            reasons.add("Matches your learning goals.");
        }
        if (learner.getCurrentLevel() != null && formation.getLevel() != null && learner.getCurrentLevel().name().equals(formation.getLevel().name())) {
            reasons.add("Matches your current level.");
        }
        if (trainingSessionRepository.existsByFormationIdAndStatusIn(formation.getId(), List.of(SessionStatus.OPEN, SessionStatus.PLANNED))) {
            reasons.add("A planned or open session is available.");
        }
        if (gap.matchPercentage() >= 60) {
            reasons.add("You already match most required skills.");
        } else if (!gap.missingSkills().isEmpty() && !completed) {
            reasons.add("Improves missing skills: " + String.join(", ", gap.missingSkills()));
        }
        if (reasons.isEmpty()) {
            reasons.add("Relevant active formation in the catalogue.");
        }

        return new ImprovementSuggestion(
                formation.getId(),
                formation.getTitle(),
                formation.getCategory().getName(),
                formation.getLevel(),
                gap.matchPercentage(),
                completed ? List.of() : gap.missingSkills(),
                reasons,
                priority(learner, formation, gap.matchPercentage(), goalsMatch, completed, progress),
                progress.progressPercentage(),
                progress.completedSessions(),
                progress.totalSessions()
        );
    }

    private ImprovementPriority priority(
            LearnerProfile learner,
            Formation formation,
            int matchPercentage,
            boolean goalsMatch,
            boolean completed,
            FormationProgressSnapshot progress
    ) {
        if (completed) {
            return ImprovementPriority.DONE;
        }
        if (progress.completedSessions() > 0) {
            return ImprovementPriority.HIGH;
        }
        if (goalsMatch && matchPercentage >= 40) {
            return ImprovementPriority.HIGH;
        }
        if (learner.getCurrentLevel() != null && formation.getLevel() != null && learner.getCurrentLevel().name().equals(formation.getLevel().name())) {
            return ImprovementPriority.MEDIUM;
        }
        return ImprovementPriority.LOW;
    }

    private Set<Long> completedFormationIds(String email, Long learnerId) {
        return formationRepository.findByActiveTrue().stream()
                .map(Formation::getId)
                .filter(formationId -> formationProgressService.snapshot(learnerId, formationId).formationComplete())
                .collect(Collectors.toSet());
    }

    private boolean goalsMatch(LearnerProfile learner, Formation formation) {
        return goalRelevance(learner, formation) > 0;
    }

    private int goalRelevance(LearnerProfile learner, Formation formation) {
        String goals = normalize(learner.getLearningGoals());
        if (!StringUtils.hasText(goals)) {
            return 0;
        }
        String title = normalize(formation.getTitle());
        String category = normalize(formation.getCategory().getName());
        if (goals.contains(title) || title.contains(goals)) {
            return 3;
        }
        if (goals.contains(category) || category.contains(goals)) {
            return 2;
        }
        if (sharesMeaningfulToken(goals, title) || sharesMeaningfulToken(goals, category)) {
            return 1;
        }
        return 0;
    }

    private boolean sharesMeaningfulToken(String left, String right) {
        Set<String> rightTokens = new java.util.HashSet<>(List.of(right.split("\\W+")));
        for (String token : left.split("\\W+")) {
            if (token.length() >= 4 && rightTokens.stream().anyMatch(rightToken -> tokensMatch(token, rightToken))) {
                return true;
            }
        }
        return false;
    }

    private boolean tokensMatch(String left, String right) {
        if (right.length() < 4) {
            return false;
        }
        return left.equals(right) || editDistanceAtMostOne(left, right);
    }

    private boolean editDistanceAtMostOne(String left, String right) {
        if (Math.abs(left.length() - right.length()) > 1) {
            return false;
        }
        int i = 0;
        int j = 0;
        int edits = 0;
        while (i < left.length() && j < right.length()) {
            if (left.charAt(i) == right.charAt(j)) {
                i++;
                j++;
            } else {
                edits++;
                if (edits > 1) {
                    return false;
                }
                if (left.length() > right.length()) {
                    i++;
                } else if (right.length() > left.length()) {
                    j++;
                } else {
                    i++;
                    j++;
                }
            }
        }
        return edits + (left.length() - i) + (right.length() - j) <= 1;
    }

    private int scoreField(String value, String field, int points, List<String> completed, List<String> missing) {
        if (StringUtils.hasText(value)) {
            completed.add(field);
            return points;
        }
        missing.add(field);
        return 0;
    }

    private String scoreMessage(int score) {
        if (score < 50) {
            return "Your profile is incomplete. Add more information to get better recommendations.";
        }
        if (score < 80) {
            return "Good start. Complete your skills and goals to improve recommendations.";
        }
        return "Your profile is well completed.";
    }

    private List<String> skillNames(Set<Skill> skills) {
        if (skills == null) {
            return List.of();
        }
        return skills.stream()
                .map(Skill::getName)
                .sorted(String.CASE_INSENSITIVE_ORDER)
                .toList();
    }

    private String normalize(String value) {
        if (value == null) {
            return "";
        }
        String normalized = Normalizer.normalize(value, Normalizer.Form.NFD)
                .replaceAll("\\p{M}", "")
                .trim()
                .toLowerCase(Locale.ROOT);
        return normalized
                .replace("frensh", "french")
                .replace("francais", "french");
    }
}
